### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by nicodemuz** [psyycker/react-translation#5]
The latest release is still giving warning such as:
```
./node_modules/@psyycker/react-translation/build/index.es.js
Module not found: Can't resolve 'react-native' in '/.../react/node_modules/@psyycker/react-translation/build'
```
This seems to be as the react-native library is not a requirement in the latest release (only in master).

**Comment by psyycker** [comment]
Hi! This is "normal" as we are doing a try/catch on getting react native package to determine which environment you are using. I fond a way to fix It by not showing this error in the console. This'll be part of the next release (0.3) which is well advanced but still a WIP.

**Comment by nicodemuz** [comment]
@psyycker I'm still getting the above warning during the build process:
```
yarn build
yarn run v1.22.5
$ craco build
Creating an optimized production build...
Compiled with warnings.

./node_modules/@psyycker/react-translation/build/index.es.js
Module not found: Can't resolve 'react-native' in '/home/nico/Projects/lms-platform-react/react/node_modules/@psyycker/react-translation/build'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

I'm using the latest package, 0.4.0:
```
yarn list | grep psyycker/react-translation
├─ @psyycker/react-translation@0.4.0
```

**Comment by psyycker** [comment]
Hi, as part of the build, it'll still show this warning that you can ignore. I'm hiding it in the console, but it's impossible to hide warning at build time. The library should work just fine
